// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	subscription "project/business/subscription"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreatePlan provides a mock function with given fields: ctx, subs
func (_m *Repository) CreatePlan(ctx context.Context, subs subscription.SubcriptionPlan) (subscription.SubcriptionPlan, error) {
	ret := _m.Called(ctx, subs)

	var r0 subscription.SubcriptionPlan
	if rf, ok := ret.Get(0).(func(context.Context, subscription.SubcriptionPlan) subscription.SubcriptionPlan); ok {
		r0 = rf(ctx, subs)
	} else {
		r0 = ret.Get(0).(subscription.SubcriptionPlan)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, subscription.SubcriptionPlan) error); ok {
		r1 = rf(ctx, subs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id int) (subscription.SubcriptionPlan, error) {
	ret := _m.Called(ctx, id)

	var r0 subscription.SubcriptionPlan
	if rf, ok := ret.Get(0).(func(context.Context, int) subscription.SubcriptionPlan); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(subscription.SubcriptionPlan)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Detail provides a mock function with given fields: ctx, id
func (_m *Repository) Detail(ctx context.Context, id int) (subscription.SubcriptionPlan, error) {
	ret := _m.Called(ctx, id)

	var r0 subscription.SubcriptionPlan
	if rf, ok := ret.Get(0).(func(context.Context, int) subscription.SubcriptionPlan); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(subscription.SubcriptionPlan)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *Repository) GetAll(ctx context.Context) ([]subscription.SubcriptionPlan, error) {
	ret := _m.Called(ctx)

	var r0 []subscription.SubcriptionPlan
	if rf, ok := ret.Get(0).(func(context.Context) []subscription.SubcriptionPlan); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]subscription.SubcriptionPlan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, subs
func (_m *Repository) Update(ctx context.Context, subs subscription.SubcriptionPlan) error {
	ret := _m.Called(ctx, subs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, subscription.SubcriptionPlan) error); ok {
		r0 = rf(ctx, subs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
