// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	omdb "project/business/omdb"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAPI provides a mock function with given fields: ctx, ImdbId
func (_m *Repository) GetAPI(ctx context.Context, ImdbId string) (omdb.GetAPI, error) {
	ret := _m.Called(ctx, ImdbId)

	var r0 omdb.GetAPI
	if rf, ok := ret.Get(0).(func(context.Context, string) omdb.GetAPI); ok {
		r0 = rf(ctx, ImdbId)
	} else {
		r0 = ret.Get(0).(omdb.GetAPI)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ImdbId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
